#!/usr/bin/env python3
"""Plot the CSV generated by optimal_backstepping_torque.cpp.

Usage:
  python3 plot_optimal_backstepping.py [csv] [--save result.png]
"""

import argparse
import csv
import os
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator


class OptimalBacksteppingLog:
    """读取、分析并绘制 optimal_backstepping_torque 的实验日志。"""

    def __init__(self, source):
        source = Path(source)
        if source.is_dir():
            source = self._find_log(source)
        self.path = source
        with source.open(newline="", encoding="utf-8") as stream:
            self.rows = list(csv.DictReader(stream))
        if not self.rows:
            raise ValueError("CSV 文件为空")
        self.limits = self._load_limits()

    def _load_limits(self):
        config = self.path.parent / "optimal_backstepping_torque.cfg"
        if not config.is_file():
            config = Path(__file__).resolve().parent / "optimal_backstepping_torque.cfg"
        limits = {
            "alpha": 0.0,
            "alpha_dot": 0.0,
            "tau": 0.0,
            "barrier": 0.9,
            "theta_initial": 0.0,
            "theta_max": 0.0,
        }
        if not config.is_file():
            return limits
        wanted = {
            "alpha_limit": "alpha",
            "alpha_dot_limit": "alpha_dot",
            "tau_limit": "tau",
            "barrier_abort_ratio": "barrier",
            "theta_initial": "theta_initial",
            "theta_max": "theta_max",
        }
        for raw_line in config.read_text(encoding="utf-8").splitlines():
            line = raw_line.split("#", 1)[0].strip()
            if "=" not in line:
                continue
            key, raw_value = (part.strip() for part in line.split("=", 1))
            if key not in wanted:
                continue
            values = [float(value) for value in raw_value.split()]
            limits[wanted[key]] = values[4] if len(values) == 6 else values[0]
        return limits

    @staticmethod
    def _find_log(directory):
        candidates = sorted(directory.glob("trial_*/optimal_backstepping_log.csv"))
        if not candidates:
            candidates = sorted(directory.glob("optimal_backstepping_log.csv"))
        if not candidates:
            raise FileNotFoundError(f"目录中没有实验日志: {directory}")
        summary = directory / "summary.json"
        if summary.is_file():
            import json
            data = json.loads(summary.read_text(encoding="utf-8"))
            valid = [x for x in data if not x.get("aborted") and not x.get("console_abort")]
            if valid:
                best = min(valid, key=lambda x: x["error_rms"])
                selected = directory / f"trial_{best['trial']:02d}" / "optimal_backstepping_log.csv"
                if selected.is_file():
                    return selected
        return candidates[-1]

    def column(self, name):
        return [float(row[name]) for row in self.rows]

    def metrics(self):
        error = self.column("error5")
        torque = self.column("tau_cmd5")
        velocity = self.column("dq5")
        barrier = self.column("barrier_ratio5")
        theta = self.column("theta_hat")
        return {
            "file": str(self.path),
            "duration_s": float(self.rows[-1]["time"]),
            "error_rms": (sum(x * x for x in error) / len(error)) ** 0.5,
            "error_peak": max(map(abs, error)),
            "velocity_peak": max(map(abs, velocity)),
            "torque_peak": max(map(abs, torque)),
            "barrier_peak": max(map(abs, barrier)),
            "theta_initial": theta[0],
            "theta_final": theta[-1],
            "theta_min": min(theta),
            "theta_peak": max(theta),
            "theta_change": theta[-1] - theta[0],
            "aborted": any(float(row["abort"]) != 0 for row in self.rows),
        }

    def plot(self, save=None):
        plot_log(self.rows, self.limits, save)


def load_csv(path):
    return OptimalBacksteppingLog(path).rows


def series(rows, name):
    return [float(row[name]) for row in rows]


def add_limits(ax, limit, label):
    if limit <= 0:
        return
    ax.axhline(limit, color="tab:red", linestyle="--", linewidth=1,
               label=f"+{label}")
    ax.axhline(-limit, color="tab:red", linestyle="--", linewidth=1,
               label=f"-{label}")


def plot_log(rows, limits=None, save=None):
    limits = limits or {"alpha": 0.0, "alpha_dot": 0.0,
                        "tau": 0.0, "barrier": 0.9,
                        "theta_initial": 0.0, "theta_max": 0.0}
    time = series(rows, "time")

    fig, axes = plt.subplots(4, 2, figsize=(13, 14), sharex=True)
    fig.suptitle("Joint 5 Optimal Backstepping Experiment")

    axes[0, 0].plot(time, series(rows, "q5"), label="q5")
    axes[0, 0].plot(time, series(rows, "qd5"), "--", label="qd5")
    axes[0, 1].plot(time, series(rows, "error5"), label="error5")
    axes[1, 0].plot(time, series(rows, "alpha5"), label="alpha5")
    add_limits(axes[1, 0], limits["alpha"], "alpha limit")
    axes[1, 1].plot(time, series(rows, "tau_raw5"), alpha=0.7,
                    label="tau raw5")
    axes[1, 1].plot(time, series(rows, "tau_cmd5"), label="tau cmd5")
    add_limits(axes[1, 1], limits["tau"], "tau limit")
    axes[2, 0].plot(time, series(rows, "barrier_ratio5"), label="barrier ratio5")
    add_limits(axes[2, 0], limits["barrier"], "abort limit")
    axes[2, 1].plot(time, series(rows, "alpha_dot5"), label="alpha dot5")
    add_limits(axes[2, 1], limits["alpha_dot"], "alpha dot limit")
    axes[3, 0].plot(time, series(rows, "theta_hat"), color="tab:purple",
                    label="theta hat")
    if limits["theta_initial"] > 0:
        axes[3, 0].axhline(limits["theta_initial"], color="tab:gray",
                           linestyle=":", linewidth=1, label="theta initial")
    if limits["theta_max"] > 0:
        axes[3, 0].axhline(limits["theta_max"], color="tab:red",
                           linestyle="--", linewidth=1, label="theta max")
    axes[3, 1].plot(time, series(rows, "z25"), label="z2_5")
    axes[3, 1].plot(time, series(rows, "dq5"), alpha=0.75, label="dq5")

    axes[0, 0].set_title("Position and reference")
    axes[0, 1].set_title("Tracking error (rad)")
    axes[1, 0].set_title("Virtual controller alpha (rad/s)")
    axes[1, 1].set_title("Controller torque (Nm)")
    axes[2, 0].set_title("Barrier ratio")
    axes[2, 1].set_title("Virtual controller derivative (rad/s^2)")
    axes[3, 0].set_title("Robust adaptive parameter theta hat")
    axes[3, 1].set_title("Velocity error state")

    for ax in axes.flat:
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=8, ncol=2)
        ax.set_xlabel("Time (s)")
        ax.xaxis.set_major_locator(MaxNLocator(nbins=8))
        ax.tick_params(axis="x", labelbottom=True)
        ax.set_xlim(time[0], time[-1])
    fig.tight_layout()

    if save:
        output_dir = os.path.dirname(os.path.abspath(save))
        os.makedirs(output_dir, exist_ok=True)
        fig.savefig(save, dpi=150)
        print(f"已保存: {save}")
    else:
        plt.show()


def main():
    script_dir = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description="绘制反步控制器实时日志或调参最佳日志")
    parser.add_argument("source", nargs="?",
                        default=script_dir / "optimal_backstepping_log.csv",
                        help="CSV 文件、trial 目录或 tuning_runs 时间戳目录")
    parser.add_argument("--save", help="保存图片路径；不填则直接显示")
    args = parser.parse_args()
    log = OptimalBacksteppingLog(args.source)
    print(log.metrics())
    log.plot(args.save)


if __name__ == "__main__":
    main()
